default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     5
  host:     "localhost" #<%= ENV['MM_DB_HOST'] %>
  username: "postgres" #<%= ENV['MM_USERNAME'] %>
  password: "postgres" #<%= ENV['MM_PASSWORD'] %>

development:
  <<: *default
  database: montessori-mozaik_development

test:
  <<: *default
  database: montessori-mozaik_test

production:
  <<: *default
  database: montessori-mozaik_production
  username: montessori-mozaik
  password: <%= ENV['MONTESSORI-MOZAIK_DATABASE_PASSWORD'] %>
